Add company_register page
comarev/comarev-dashboard pull request #24
Opened 2021-11-08 22:40 UTC by m-pereira

Closes: https://github.com/comarev/comarev-dashboard/issues/14

#### What?

- [x] Add [react-hook-form](https://react-hook-form.com/) lib
- [x] Add `CompanyRegister` page
- [x] Add `companies/new` route 
- [ ] Add `CompanyForm` component

#### Why?

Where admins will be able to create new campaigns

#### How it has been tested?

Integration specs for those components with jest

2021-11-08 22:43 UTC, m-pereira commented on src/routes/index.js
> +        <SecureRoute path='/companies' exact component={Dashboard} admin />
Just to test the redirect, it will be replaced for the right route when this [pr](https://github.com/comarev/comarev-dashboard/pull/21) is merged

2021-11-24 21:07 UTC, mjpancheri approved these changes
Looks good to me.

2021-11-30 13:11 UTC, belgamo requested changes
Nice job!

2021-11-30 13:11 UTC, belgamo commented on package.json
> +    "prettier": "^2.4.1"
You don't need prettier in an app created with `create-react-app` boilerplate.

2021-11-30 13:11 UTC, belgamo commented on src/components/companies-list/companies-list.js
> +            <TableCell align='right'>Desconto&nbsp;</TableCell>
Remove this `&nbsp;`

2021-11-30 13:11 UTC, belgamo commented on src/components/form_error/styles.js
> +  background-color: ${theme.palette.warning.light};
We should add a stronger red color here.

2021-11-30 13:11 UTC, belgamo commented on src/pages/companies-list/companies-list.js
> +        <h2>Empresas</h2>
Make sure these titles are aligned to the content here and on the other pages as well.

2021-11-30 13:11 UTC, belgamo commented on src/service/company.js
> +const parseCompany = (payload) => {
Add a snapshot test for it.

2021-11-30 13:11 UTC, belgamo commented on src/pages/companies/form/styles.js
> +  background: #fff;
Why do you need a background color here?

2021-11-30 13:11 UTC, belgamo commented on src/pages/companies/form/styles.js
> +  padding-bottom: 30px;
Use `theme.spacing `from material UI to keep the design consistency.

2021-11-30 13:11 UTC, belgamo commented on src/service/company.js
> +const registerCompany = async ({
I think we have an example testing the service layer.

2021-11-30 13:13 UTC, belgamo commented
Also, remember to rename the files to the js pattern using dash instead of the underscore.

2021-12-15 18:14 UTC, RenanRSilva approved these changes

2022-01-31 16:23 UTC, merged