Fix/toaster appearing when logging out
comarev/comarev-dashboard pull request #65
Opened 2022-03-07 19:24 UTC by Isaac-alencar

Closes:[ Fix toaster appearing when logging out #53](https://github.com/comarev/comarev-dashboard/issues/53)

References: <issue-link>/<pr-link>

#### What?

- Change the logic behind the secure-route component to display "Insufficient permissions" toaster 
message only with logged users

#### Why?

- To fix unwanted display of an toaster with "Insufficient permissions" message when users logging out from application

#### How to test it?

- Sign In with any available account and try to Sign out, then the toaster should not be displayed

2022-03-10 16:43 UTC, belgamo requested changes

2022-03-10 16:43 UTC, belgamo commented on README.md
This file should not be changed on this PR...

2022-03-10 16:59 UTC, belgamo approved these changes
Great PR! Thanks :D

2022-03-10 16:59 UTC, merged

2022-03-14 12:51 UTC, wenderjean commented on src/routes/secure-route.component.js
>    const userRoles = USER_ROLES.filter((role) => user[role]);
Sei que não é o foco desse PR mas talvez valha a pena criar uma abstração para encapsular os comportamentos referentes a `USER_ROLES`.