tests: add tests to RoleFilter component
comarev/comarev-dashboard pull request #71
Opened 2022-03-18 17:47 UTC by Isaac-alencar

Closes: [issue-52](https://github.com/comarev/comarev-dashboard/issues/52)

References: <issue-link>/<pr-link>

#### What?

- Add tests for RoleFilter component
#### Why?

- To ensure the component is returning null or an given element depending if user has or not proper roles

#### How to test it?

```bash
# to run all tests suits
yarn test

# press 'a' to run all tests and see tests for RoleComponents passing
```

2022-03-18 18:13 UTC, geeksilva97 commented on src/components/role-filter/__tests__/role-filter.component.test.js
> +
```suggestion
```

2022-03-18 18:25 UTC, belgamo requested changes
Overall looks great! As you're here adding tests, I'll take advantage and ask you to abstract the logic into a custom hook, something like `useRoleFilter` return the `hasPermission`. Then you just have to call this hook in the component and we can reuse this hook over our app.

2022-03-18 18:25 UTC, belgamo commented on src/components/role-filter/__tests__/role-filter.component.test.js
> +jest.mock('react-redux', () => ({
You don't need to mock this. Use our `wrapper` instead.

2022-03-18 18:25 UTC, belgamo commented on src/components/role-filter/__tests__/role-filter.component.test.js
> +
Remove empty lines :nail_care:

2022-04-22 23:28 UTC, Isaac-alencar commented
Not quite sure if what I've done on `useRoleFilter` tests is the more appropriated approach. Following the documentation of `@testing-library/react-hooks` in [this section](https://react-hooks-testing-library.com/usage/advanced-hooks), to render hooks that needs information from some provider(_e.g redux_), we need to use a wrapper, and this wrapper needs to be simple as:
```jsx
const wrapper = ({ children }) => <CounterStepProvider step={2}>{children}</CounterStepProvider>
```
But our wrapper returns a rendered element and didn't work as expected. If you guys have a tip to improve my tests I will be thankful

2022-05-30 15:04 UTC, belgamo commented
> Not quite sure if what I've done on `useRoleFilter` tests is the more appropriated approach. Following the documentation of `@testing-library/react-hooks` in [this section](https://react-hooks-testing-library.com/usage/advanced-hooks), to render hooks that needs information from some provider(_e.g redux_), we need to use a wrapper, and this wrapper needs to be simple as:
> 
> ```js
> const wrapper = ({ children }) => <CounterStepProvider step={2}>{children}</CounterStepProvider>
> ```
> 
> But our wrapper returns a rendered element and didn't work as expected. If you guys have a tip to improve my tests I will be thankful

I've pushed a commit refactoring the `wrapper` component to support hooks.

2022-05-30 15:06 UTC, merged